# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncriptarDecriptar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chave',
            field=models.CharField(max_length=200, null=True, verbose_name='chave'),
        ),
    ]
