# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncriptarDecriptar', '0002_usuario_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='chave'),
        ),
    ]
