# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncriptarDecriptar', '0003_auto_20171013_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave',
            field=models.CharField(max_length=200, null=True, verbose_name='chave'),
        ),
    ]
